-- AlterTable
ALTER TABLE `Specialty` ADD COLUMN `date01` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `date02` DATETIME(3) NULL;

-- AlterTable
ALTER TABLE `User` MODIFY `birthdate` DATETIME(3) NULL;
